### ISSUE TITLE
SIM placing students back into courses after manual removal

### ISSUE THREAD

**Issue by zhisu34** [ltoews/sim_avs#15]
Hi Lorin,

I withdrew a number of students and after doing a course sync in SIM, the students were placed back in.

Jantzen, Austin is one of them.

![image](https://user-images.githubusercontent.com/130780475/232099218-385512d2-7344-47ac-a4a2-ca31b0bd9448.png)

I am thinking there are quite of few that were placed back into courses.

**Comment by ltoews** [comment]
The sync function was really only intended to bring SIM up to date with the pre-existing enrolments in BS. My expectation was that all enrolments would be managed from SIM from that point on, so I didn't anticipate this scenario. That said, this is still something that we don't want the sync to do. I will take a look at it right away.

**Comment by ltoews** [comment]
This is a test reply to the email from the issue tracker

**Comment by ltoews** [comment]
Problem was not in code, but with staff manually removing students from courses in BS but not telling SIM that the students was unenrolled. When SIM found that a student that it believed was in a course was NOT actually in the course, it put them back in.
